### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by prg-04** [prg-04/camera-rental-frontend#10]
My team has 4 members, and [this](https://github.com/users/prg-04/projects/4) is our project board. The members are:

- [Maurice](https://github.com/coker2019)
- [Mumbere](https://github.com/mumbereh)
- [Mustakim](https://github.com/firepicaso)
- [Evans](https://github.com/prg-04)

![image](https://github.com/prg-04/camera-rental-frontend/assets/103628308/5590c046-2bae-4d6f-9cc8-23c3bd3f12df)

**Comment by Meltrust** [comment]
Hi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have descriptions✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] Your kanban board is missing a column named "in review".  Kindly add it in order to meet the requirements.

- [ ] OPTIONAL: Your total points are about 12.  However, this project is rated for 60+ hours.  I suggest you adjust the times to be more realistic.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- New required column has been added✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
